security:
  oauth2:
    client:
      clientId: YOUR_CLIENTID
      clientSecret: YOUR_SECRET
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize?scope=public_repo
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://api.github.com/user
